development:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: gitpit_web
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  username: root
  password: password
  database: gitpit_web_test
  encoding: utf8

production:
  adapter: postgresql
  pool: 5
  username: root
  password: password
  database: gpti_web
  encoding: utf8
